name: Tests

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  run_unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Environment
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: env.yml
          init-shell: bash
      
      - name: Run my_utils Tests
        shell: bash -l {0}
        run: |
          export PYTHONPATH=src
          python test/unit/test_my_utils.py
      
      - name: Run unit_testing Tests
        shell: bash -l {0}
        run: |
          export PYTHONPATH=src
          python test/unit/unit_testing.py
  
  run_func_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Environment
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: env.yml
          init-shell: bash
      
      - name: Run my_utils Tests
        shell: bash -l {0}
        working-directory: ./test/func
        run: bash my_utils_func_testing.sh
      
      - name: Run Print Fires Tests
        shell: bash -l {0}
        working-directory: ./test/func
        run: bash test_print_fires.sh
  
  run_linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: env.yml
          init-shell: bash
      - run: pycodestyle $(git ls-files "*.py")
        shell: bash -l {0}